### PR TITLE
optionally handle timeouts in observers

### PR DESCRIPTION
**Pull request by matthgt**
Allow observers to mark the state change as handled. This causes Rack::Timeout to not perform its default handling for the states `expired` and `timed_out` and ultimately causes it not to raise an error in the long running request.

I'm using this to investigate which requests are slow without the risks of killing a request in the middle of its execution.

### CODE REVIEW

**Comment by wuputah** [comment]
I had some reservations but upon review I think this is a good change. The only thing it's lacking is documentation.

**Comment by wuputah** [comment]
(And tests would be amazing too...)

**Comment by modosc** [comment]
having a single`timed_out` handler that is called for both `expired` and `timed_out` is a bit confusing - would it make sense to either add similar code for a handler named `expired` or to use a totally different name for this handler?

**Comment by schneems** [comment]
If this is a bugfix can you give us a [reproduction example](http://codetriage.com/example_app) or a test that fails on master and passes on this branch?

**Pull request closed without merging**
