### PR TITLE
Support Rails 6

### PR DESCRIPTION
**Pull request by amatsuda**
This patch adds support for upcoming Rails 6.

### CODE REVIEW

**Comment by wuputah** [comment]
:+1: thanks! this warrants a release. have you tried it will Rails 6 and all is well?

**Comment by lfittl** [comment]
@wuputah As one data point, I've tried it with Rails 6 and it seems to work as expected.

**Comment by wuputah** [comment]
thanks @lfittl ! I need to cut a release. 😁

**Comment by RaviAsnani** [comment]
@wuputah Could you please release a version with this PR. Thanks!

**Pull request merged**
